<?php

/**
 * Theme setup.
 */

namespace App;

use App\Constants\ThemeConstant;
use App\Customizers\ThemeColor;
use Illuminate\Support\Facades\Vite;

/**
 * Inject styles into the block editor.
 *
 * @return array
 */
add_filter('block_editor_settings_all', function ($settings) {
    $style = Vite::asset('resources/css/editor.css');

    $settings['styles'][] = [
        'css' => "@import url('{$style}')",
    ];

    return $settings;
});

/**
 * Inject scripts into the block editor.
 *
 * @return void
 */
add_action('admin_head', function () {
    if (! get_current_screen()?->is_block_editor()) {
        return;
    }

    if (! Vite::isRunningHot()) {
        $dependencies = json_decode(Vite::content('editor.deps.json'));

        foreach ($dependencies as $dependency) {
            if (! wp_script_is($dependency)) {
                wp_enqueue_script($dependency);
            }
        }
    }
    echo Vite::withEntryPoints([
        'resources/js/editor.js',
    ])->toHtml();
});

/**
 * Use the generated theme.json file.
 *
 * @return string
 */
add_filter('theme_file_path', function ($path, $file) {
    return $file === 'theme.json'
        ? public_path('build/assets/theme.json')
        : $path;
}, 10, 2);

/**
 * Disable on-demand block asset loading.
 *
 * @link https://core.trac.wordpress.org/ticket/61965
 */
add_filter('should_load_separate_core_block_assets', '__return_false');

/**
 * Register the initial theme setup.
 *
 * @return void
 */
add_action('after_setup_theme', function () {
    /**
     * Disable full-site editing support.
     *
     * @link https://wptavern.com/gutenberg-10-5-embeds-pdfs-adds-verse-block-color-options-and-introduces-new-patterns
     */
    remove_theme_support('block-templates');

    /**
     * Disable the default block patterns.
     *
     * @link https://developer.wordpress.org/block-editor/developers/themes/theme-support/#disabling-the-default-block-patterns
     */
    remove_theme_support('core-block-patterns');

    /**
     * Enable plugins to manage the document title.
     *
     * @link https://developer.wordpress.org/reference/functions/add_theme_support/#title-tag
     */
    add_theme_support('title-tag');

    /**
     * Enable post thumbnail support.
     *
     * @link https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
     */
    add_theme_support('post-thumbnails');

    /**
     * Enable responsive embed support.
     *
     * @link https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#responsive-embedded-content
     */
    add_theme_support('responsive-embeds');

    /**
     * Enable HTML5 markup support.
     *
     * @link https://developer.wordpress.org/reference/functions/add_theme_support/#html5
     */
    add_theme_support('html5', [
        'caption',
        'comment-form',
        'comment-list',
        'gallery',
        'search-form',
        'script',
        'style',
    ]);

    add_theme_support('custom-logo', [
        'height' => 32,
        'width' => 220,
        'flex-height' => true,
        'flex-width' => true,
    ]);

    /**
     * Enable selective refresh for widgets in customizer.
     *
     * @link https://developer.wordpress.org/reference/functions/add_theme_support/#customize-selective-refresh-widgets
     */
    add_theme_support('customize-selective-refresh-widgets');
}, 20);

add_action('after_setup_theme', function () {
    load_theme_textdomain('a-ripple-song', get_template_directory() . '/resources/lang');
});

/**
 * Enqueue frontend assets generated by Vite.
 */
add_action('wp_enqueue_scripts', function () {
    if (! class_exists(Vite::class)) {
        return;
    }

    try {
        $cssUrl = Vite::asset('resources/css/app.css');
        $jsUrl = Vite::asset('resources/js/app.js');

        if ($cssUrl) {
            wp_enqueue_style('aripplesong-app', $cssUrl, [], null);
        }

        if (defined('IFRAME_REQUEST') && IFRAME_REQUEST) {
            return;
        }

        if (! $jsUrl) {
            return;
        }

        wp_enqueue_script('aripplesong-app', $jsUrl, ['wp-i18n'], null, true);
        wp_set_script_translations('aripplesong-app', 'a-ripple-song', get_template_directory() . '/resources/lang');

        $currentPostId = is_singular() ? get_queried_object_id() : 0;
        $currentPostType = $currentPostId ? get_post_type($currentPostId) : '';
        $latestPlaylistData = function_exists('aripplesong_get_latest_playlist_data')
            ? \aripplesong_get_latest_playlist_data(10)
            : [
                'episodes' => [],
                'signature' => '',
            ];

        wp_localize_script('aripplesong-app', 'aripplesongData', [
            'restUrl' => esc_url_raw(rest_url()),
            'restNonce' => wp_create_nonce('wp_rest'),
            'siteUrl' => esc_url_raw(home_url('/')),
            'latestPlaylistSignature' => $latestPlaylistData['signature'] ?? '',
            'latestPlaylistEpisodes' => $latestPlaylistData['episodes'] ?? [],
            'ajax' => [
                'url' => esc_url_raw(admin_url('admin-ajax.php')),
                'nonce' => wp_create_nonce('aripplesong-ajax'),
                'postId' => $currentPostId,
                'postType' => $currentPostType,
            ],
            'theme' => [
                'lightTheme' => ThemeColor::getLightTheme(),
                'darkTheme' => ThemeColor::getDarkTheme(),
                'lightThemes' => ThemeColor::getLightThemeSlugs(),
                'darkThemes' => ThemeColor::getDarkThemeSlugs(),
                'palette' => ThemeConstant::PALETTE,
            ],
        ]);
    } catch (\Throwable $throwable) {
        error_log('Failed to enqueue Vite assets: '.$throwable->getMessage());
    }
}, 100);

/**
 * Mark Vite JavaScript entrypoints as ES modules.
 */
add_filter('script_loader_tag', function ($tag, $handle, $src) {
    if ($handle === 'aripplesong-app') {
        return str_replace('<script ', '<script type="module" ', $tag);
    }

    return $tag;
}, 10, 3);
